# Generated by Django 5.0.1 on 2025-05-27 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spk', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='framework',
            name='community',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='framework',
            name='learning_time',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='framework',
            name='maintenance',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='framework',
            name='performance',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='framework',
            name='scalability',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='criteria',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='criteria',
            name='weight',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='framework',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='framework',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='frameworkscore',
            name='value',
            field=models.FloatField(default=0),
        ),
        migrations.AlterUniqueTogether(
            name='frameworkscore',
            unique_together={('framework', 'criteria')},
        ),
    ]
